# Generated by Django 5.2.10 on 2026-01-28 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("musicals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=50)),
                ("open_at", models.DateTimeField()),
                ("url", models.URLField(blank=True, null=True)),
                ("is_custom", models.BooleanField(default=False)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "musical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="musicals.musical",
                    ),
                ),
            ],
        ),
    ]
