# Generated by Django 5.2.10 on 2026-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musical',
            name='kopis_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='kopis_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
