# Generated by Django 5.2.10 on 2026-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0002_alter_actor_name_alter_musical_kopis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
