# Generated by Django 5.2.10 on 2026-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicals", "0003_alter_musical_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actor",
            name="source_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
