# Generated by Django 5.2.10 on 2026-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicals", "0004_actor_external_link_actor_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="musical",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="musicals", to="musicals.actor"
            ),
        ),
    ]
