# Generated by Django 5.2.10 on 2026-02-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("musicals", "0005_musical_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="external_link",
        ),
    ]
